import {
  FaGem,
  FaBoxes,
  FaMoneyBillWave,
  FaArrowDown,
  FaArrowUp,
} from "react-icons/fa";

export const VOUCHER_CONFIGS = {
  "rough-purchase": {
    id: "rough-purchase",
    slug: "rough-purchase",
    name: "Rough Purchase",
    group: "trade",
    type: "Purchase",
    category: "Rough",
    crDr: "DR",
    color: "#B45309",
    bg: "#FEF3C7",
    border: "#FDE68A",
    tagline: "Rough Diamond Inward & Procurement Voucher",
    icon: FaGem,
  },
  "rough-sale": {
    id: "rough-sale",
    slug: "rough-sale",
    name: "Rough Sale",
    group: "trade",
    type: "Sale",
    category: "Rough",
    crDr: "CR",
    color: "#15803D",
    bg: "#DCFCE7",
    border: "#BBF7D0",
    tagline: "Rough Diamond Outward & Consignment Sale Voucher",
    icon: FaGem,
  },
  "polish-purchase": {
    id: "polish-purchase",
    slug: "polish-purchase",
    name: "Polish Purchase",
    group: "trade",
    type: "Purchase",
    category: "Polish",
    crDr: "DR",
    color: "#B45309",
    bg: "#FEF3C7",
    border: "#FDE68A",
    tagline: "Polished Diamond / Certified Stone Purchase Voucher",
    icon: FaBoxes,
  },
  "polish-sale": {
    id: "polish-sale",
    slug: "polish-sale",
    name: "Polish Sale",
    group: "trade",
    type: "Sale",
    category: "Polish",
    crDr: "CR",
    color: "#15803D",
    bg: "#DCFCE7",
    border: "#BBF7D0",
    tagline: "Polished Diamonds Bourse & Export Sale Voucher",
    icon: FaBoxes,
  },
  "lgd-purchase": {
    id: "lgd-purchase",
    slug: "lgd-purchase",
    name: "LGD Purchase",
    group: "trade",
    type: "Purchase",
    category: "LGD",
    crDr: "DR",
    color: "#7C3AED",
    bg: "#F3E8FF",
    border: "#E9D5FF",
    tagline: "Lab Grown Diamond (CVD/HPHT) Inward Voucher",
    icon: FaGem,
  },
  "lgd-sale": {
    id: "lgd-sale",
    slug: "lgd-sale",
    name: "LGD Sale",
    group: "trade",
    type: "Sale",
    category: "LGD",
    crDr: "CR",
    color: "#0D9488",
    bg: "#CCFBF1",
    border: "#99F6E4",
    tagline: "Lab Grown Diamond (CVD/HPHT) Outward Sale Voucher",
    icon: FaGem,
  },
  "expense": {
    id: "expense",
    slug: "expense",
    name: "Expense",
    group: "finance",
    type: "Expense",
    category: "Expense",
    crDr: "DR",
    color: "#DC2626",
    bg: "#FEE2E2",
    border: "#FECACA",
    tagline: "Operational, Brokerage, Assorting & Office Expenses",
    icon: FaMoneyBillWave,
  },
  "payment-entry": {
    id: "payment-entry",
    slug: "payment-entry",
    name: "Payment Entry",
    group: "finance",
    type: "Payment",
    category: "Payment",
    crDr: "DR",
    color: "#C026D3",
    bg: "#FAE8FF",
    border: "#F5D0FE",
    tagline: "Supplier / Vendor Payment Settlement Voucher",
    icon: FaArrowDown,
  },
  "payment-receive": {
    id: "payment-receive",
    slug: "payment-receive",
    name: "Payment Receive",
    group: "finance",
    type: "Receive",
    category: "Receive",
    crDr: "CR",
    color: "#2563EB",
    bg: "#DBEAFE",
    border: "#BFDBFE",
    tagline: "Customer / Buyer Inflow & Receipt Voucher",
    icon: FaArrowUp,
  },
};

export const EXPENSE_HEADS = [
  "Brokerage & Commission",
  "Assorting & Labor Charges",
  "Office Rent & Utilities",
  "GIA / IGI Certification Fees",
  "Freight, Shipping & Courier",
  "Bank & Financial Charges",
  "Legal & Professional Fees",
  "Staff Salary & Wages",
  "Customs & Clearing Charges",
  "General / Miscellaneous",
];

export const STORAGE_KEY = "royal_rays_signature_vouchers_v1";
